AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Transaction Visualizer - Backend Infrastructure Stack

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Resources:
  ##########################################################################
  #                         Backend Nested Stack                          #
  ##########################################################################
  BackendStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../src/backend/template.yaml
      Parameters:
        DSQLEndpoint: !ImportValue
          'Fn::Sub': 'dsql-${Environment}-ClusterEndpoint'
        UserPoolId: !ImportValue
          'Fn::Sub': 'stateful-${Environment}-UserPoolId'
        UserPoolClientId: !ImportValue
          'Fn::Sub': 'stateful-${Environment}-UserPoolClientId'

Outputs:
  ApiGatewayURL:
    Description: URL for the API Gateway
    Value: !GetAtt BackendStack.Outputs.ApiGatewayURL
    Export:
      Name: !Sub 'backend-ApiGatewayURL'
