import { DsqlSigner } from '@aws-sdk/dsql-signer'
import { drizzle, NodePgDatabase } from 'drizzle-orm/node-postgres'
import pg from 'pg'
import * as schema from './schema.js'

const { Pool } = pg

type Schema = typeof schema

let db: NodePgDatabase<Schema> | null = null

/**
 * Returns a singleton Drizzle client connected to Aurora DSQL.
 * Aurora DSQL uses IAM authentication — the password is a short-lived
 * token generated by DsqlSigner using the current Lambda execution role.
 */
export async function getDb(): Promise<NodePgDatabase<Schema>> {
  if (db) return db

  const endpoint = process.env.DSQL_ENDPOINT
  const region = process.env.AWS_REGION ?? 'us-east-1'

  if (!endpoint) {
    throw new Error('DSQL_ENDPOINT environment variable is not set')
  }

  const signer = new DsqlSigner({ hostname: endpoint, region })
  const token = await signer.getDbConnectAdminAuthToken()

  const pool = new Pool({
    host: endpoint,
    port: 5432,
    user: 'admin',
    password: token,
    database: 'postgres',
    ssl: { rejectUnauthorized: true },
    max: 1, // keep Lambda concurrency-safe
  })

  db = drizzle(pool, { schema })
  return db
}
