AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Transaction Visualizer - S3 File Storage

Parameters:
  AppName:
    Type: String
    Description: Name of the application

  Environment:
    Type: String
    Description: Deployment environment

Resources:
  ##########################################################################
  #                              S3 Bucket                               #
  ##########################################################################
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-files-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Project
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  ##########################################################################
  #                          Frontend S3 Bucket                          #
  ##########################################################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-frontend-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FilesBucketName:
    Description: Name of the files S3 bucket
    Value: !Ref FilesBucket

  FilesBucketArn:
    Description: ARN of the files S3 bucket
    Value: !GetAtt FilesBucket.Arn

  FrontendBucketName:
    Description: Name of the frontend S3 bucket
    Value: !Ref FrontendBucket

  FrontendBucketArn:
    Description: ARN of the frontend S3 bucket
    Value: !GetAtt FrontendBucket.Arn
